Add refreshPeriod to external tools and scripts for improved update management

diff --git a/.chezmoiscripts/run_onchange_00_core.sh.tmpl b/.chezmoiscripts/run_onchange_00_core.sh.tmpl
--- a/.chezmoiscripts/run_onchange_00_core.sh.tmpl
+++ b/.chezmoiscripts/run_onchange_00_core.sh.tmpl
@@ -1,4 +1,10 @@
 #!/bin/sh
+
 {{ if eq (lookPath "starship") "" -}}
 curl -sS https://starship.rs/install.sh | STARSHIP_INSTALL=true sh -s -- -y --bin-dir="$HOME/.local/bin/"
 {{ end -}}
+
+if ! command -v ~/.local/bin/mise &>/dev/null; then
+  echo "mise not found. Installing..."
+  curl -sL https://mise.run | sh
+fi
